version: '3.8'

services:
  portal:
    container_name: ${COMPOSE_PROJECT_NAME}-portal
    build:
      context: .
      dockerfile: ${NICE_AGENT_ROLE}.Dockerfile
    image: digicatapult/nice-agent-portal-${NICE_AGENT_ROLE}:${NICE_AGENT_VER-latest}
    restart: on-failure
    depends_on:
      veritable:
        condition: service_healthy
    ports:
      - '${NICE_PORT_HOST-3000}:3000'
    volumes:
      - ./.env.${COMPOSE_PROJECT_NAME}.local:/app/.env
    environment:
      - CLOUDAGENT_HOST
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - STATIC_ROOT
      - DATABASE_URL
      - ISSUER_HOST
      - ISSUER_PORT
    env_file:
      - .env.${COMPOSE_PROJECT_NAME}.local
    command: [sh, -c, 'npx prisma migrate deploy && npm start']
    networks: ['nice-net', 'agent-net']

  veritable:
    container_name: ${COMPOSE_PROJECT_NAME}-veritable
    image: digicatapult/veritable-cloudagent:${VERITABLE_AGENT_VER-latest}
    restart: on-failure
    depends_on:
      ipfs:
        condition: service_healthy
      opa:
        condition: service_started
      postgres:
        condition: service_healthy
      postgres-veritable:
        condition: service_healthy
    volumes:
      - ./cloudagentConfig.json:/config.json
      - veritable-filesystem:/root/.afj
    ports:
      #  - '5022:5002'
      #  - '5023:5003'
      - '${VERITABLE_PORT_HOST-3010}:3000'
    environment:
      - AFJ_REST_LOG_LEVEL=1
    # or via command line arguments
    command: --endpoint "http://${COMPOSE_PROJECT_NAME}-veritable:5002" "ws://${COMPOSE_PROJECT_NAME}-veritable:5003" --ipfs-origin http://ipfs:5001 --opa-origin http://opa:8181 --webhook-url "${PORTAL_BASE_URL}/api/webhooks" --auto-accept-connections true --auto-accept-credentials always --config /config.json --postgres-port ${VERITABLE_PG_PORT} --postgres-host ${VERITABLE_PG_HOST}
    networks: ['nice-net', 'agent-net']

  fetch-ai-adapter:
    container_name: ${COMPOSE_PROJECT_NAME}-nice-fetch-ai-adapter
    image: digicatapult/nice-fetch-ai-adapter:${NICE_FETCH_AI_ADAPTER-latest}
    restart: on-failure
    ports:
      - '${NICE_FETCH_AI_ADAPTER_PORT_HOST-8000}:8000'
    environment:
      - AFJ_REST_LOG_LEVEL=1
    networks: ['nice-net', 'agent-net']

  ipfs:
    container_name: ${COMPOSE_PROJECT_NAME}-ipfs
    image: ipfs/kubo:${KUBO_AGENT_VER-release}
    restart: on-failure
    # ports:
    #   - "4001:4001" # ipfs swarm - expose if needed/wanted
    #   - "5001:5001" # ipfs api - expose if needed/wanted
    #   - '8080:8080' # ipfs gateway - expose if needed/wanted
    volumes:
      - ipfs-data:/data/ipfs
      - ./ipfs-init.sh:/container-init.d/0-ipfs-init.sh
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 0s
    networks: ['nice-net', 'agent-net']
    #environment:
    #  - IPFS_LOGGING=info

  opa:
    container_name: ${COMPOSE_PROJECT_NAME}-opa
    image: openpolicyagent/opa:0.63.0-static
    restart: on-failure
    #ports:
    #  - '8181:8181'
    command: run --server --log-level debug
    networks: ['agent-net']

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:16.2-alpine
    restart: on-failure
    ports:
      - ${DB_PORT_HOST}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test:
        ['CMD-SHELL', 'PGUSER=${DB_USERNAME}', pg_isready", '-d', '${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 0s
    networks: ['agent-net']

  postgres-veritable:
    image: postgres:16.2-alpine
    restart: on-failure
    volumes:
      - veritable-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'PGUSER=postgres', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 0s
    networks:
      - agent-net
volumes:
  pg-data:
  ipfs-data:
  ipfs-cluster-data:
  veritable-filesystem:
  veritable-postgres:

networks:
  nice-net:
    name: nice-net
  agent-net:
